/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FormSubmitHandler } from "./components/stripe-card-element/stripe-card-element";
export namespace Components {
    interface StripeCardElement {
        "handleSubmit"?: FormSubmitHandler;
        /**
          * Get Stripe.js, and initialize elements
          * @param publishableKey
         */
        "initStripe": (publishableKey: string) => Promise<void>;
        /**
          * Your Stripe publishable API key.
         */
        "publishableKey": string;
        /**
          * Set form submit event function
          * @param handler FormSubmitHandler
         */
        "setFormSubmitHandler": (handler: FormSubmitHandler) => Promise<void>;
    }
}
declare global {
    interface HTMLStripeCardElementElement extends Components.StripeCardElement, HTMLStencilElement {
    }
    var HTMLStripeCardElementElement: {
        prototype: HTMLStripeCardElementElement;
        new (): HTMLStripeCardElementElement;
    };
    interface HTMLElementTagNameMap {
        "stripe-card-element": HTMLStripeCardElementElement;
    }
}
declare namespace LocalJSX {
    interface StripeCardElement {
        "handleSubmit"?: FormSubmitHandler;
        /**
          * Your Stripe publishable API key.
         */
        "publishableKey"?: string;
    }
    interface IntrinsicElements {
        "stripe-card-element": StripeCardElement;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stripe-card-element": LocalJSX.StripeCardElement & JSXBase.HTMLAttributes<HTMLStripeCardElementElement>;
        }
    }
}
